#!/bin/sh
# usage: vgrab_to_tft [video device (default=/dev/video0)]
# requires imagemagick (convert) and a netcat (nc)

HOST=esp2

PN=$(readlink -f -n "$0") || PN="$0"
DN=$(dirname "$PN")
TN=$(mktemp)

"$DN"/vgrab "$TN" $1 &&\
    convert "$TN" -rotate 90 "$TN.rgb" &&\
    "$DN"/to_565 "$TN.rgb" > "$TN" &&\
    cat "$TN" | nc $HOST 9341 &&\
    rm -f "$TN" "$TN.rgb"

